version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8u232-jdk
    resource_class: xlarge
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y cmake
      - checkout
      - run: ant clean
      - run: ant dist_internal
      - persist_to_workspace:
          root: .
          paths:
            - voltdb
            - obj
  junit_regression_h1:
    docker:
      - image: circleci/openjdk:8u232-jdk
    resource_class: xlarge
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y cmake
      - checkout
      - attach_workspace:
          at: .
      - run: ant junit_regression_h1
      - store_test_results:
          path: obj/release/testoutput
  junit_regression_h2:
    docker:
      - image: circleci/openjdk:8u232-jdk
    resource_class: xlarge
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y cmake
      - checkout
      - attach_workspace:
          at: .
      - run: ant junit_regression_h2
      - store_test_results:
          path: obj/release/testoutput
  junit_other_p1:
    docker:
      - image: circleci/openjdk:8u232-jdk
    resource_class: xlarge
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y cmake
      - checkout
      - attach_workspace:
          at: .
      - run: ant junit_other_p1
      - store_test_results:
          path: obj/release/testoutput
  junit_other_p2:
    docker:
      - image: circleci/openjdk:8u232-jdk
    resource_class: xlarge
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y cmake
      - checkout
      - attach_workspace:
          at: .
      - run: ant junit_other_p2
      - store_test_results:
          path: obj/release/testoutput
  junit_other_p3:
    docker:
      - image: circleci/openjdk:8u232-jdk
    resource_class: xlarge
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y cmake
      - checkout
      - attach_workspace:
          at: .
      - run: ant junit_other_p3
      - store_test_results:
          path: obj/release/testoutput
  junit_other_p4:
    docker:
      - image: circleci/openjdk:8u232-jdk
    resource_class: xlarge
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y cmake
      - checkout
      - attach_workspace:
          at: .
      - run: ant junit_other_p4
      - store_test_results:
          path: obj/release/testoutput
  package:
    docker:
      - image: circleci/openjdk:8u232-jdk
    resource_class: xlarge
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install -y cmake
      - checkout
      - attach_workspace:
          at: .
      - store_artifacts:
          path: obj/release/voltdb-community-*.tar.gz

workflows:
  version: 2
  build_test_package:
    jobs:
      - build
      - junit_regression_h1:
          requires:
            - build
      - junit_regression_h2:
          requires:
            - build
      - junit_other_p1:
          requires:
            - build
      - junit_other_p2:
          requires:
            - build
      - junit_other_p3:
          requires:
            - build
      - junit_other_p4:
          requires:
            - build
      - package:
          requires:
            - junit_regression_h1
            - junit_regression_h2
            - junit_other_p1
            - junit_other_p2
            - junit_other_p3
            - junit_other_p4