version: 2

jobs:
  dist:
    docker:
      - image: ubuntu:16.04
    resource_class: xlarge
    steps:
      - run: apt-get update
      - run: apt-get install -y openjdk-8-jdk-headless ant build-essential cmake python git
      - checkout
      - run: ant clean
      - run: ant dist
      - run: cp obj/release/voltdb-community-*.tar.gz obj/release/mode-voltdb-community.tar.gz
      - persist_to_workspace:
          root: .
          paths:
            - voltdb
            - obj
      - store_artifacts:
          path: obj/release/mode-voltdb-community.tar.gz
          destination: release
  check_quick:
    docker:
      - image: circleci/openjdk:8-jdk
    resource_class: xlarge
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: ant licensecheck junit_quick
      - store_test_results:
          path: obj/release/testoutput

workflows:
  version: 2
  build_test_package:
    jobs:
      - dist
      - check_quick:
          requires:
            - dist
