name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04

    steps:
    - name: update package info
      run: sudo apt-get update
    - name: install dependencies
      run: sudo apt-get install -y openjdk-8-jdk-headless ant build-essential cmake python git
    - uses: actions/checkout@v1
    - name: build voltdb
      run: ant clean dist
    - name: normalize build tarball filename
      run: cp obj/release/voltdb-community-*.tar.gz obj/release/mode-voltdb-community.tar.gz
    - name: upload build tarball
      uses: actions/upload-artifact@v1
      with:
        name: mode-voltdb-community.tar.gz
        path: obj/release/mode-voltdb-community.tar.gz
